# Generated by Django 6.1.1 on 2026-09-17 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qurilma nomi')),
                ('device_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Maxsus Token')),
                ('is_online', models.BooleanField(default=False, verbose_name='Aloqadami')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.TextField(verbose_name='Buyruq (CMD/Bash)')),
                ('response_text', models.TextField(blank=True, null=True, verbose_name='Natija')),
                ('is_executed', models.BooleanField(default=False, verbose_name='Bajarildimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='remote.device', verbose_name='Qurilma')),
            ],
        ),
    ]
