# Generated by Django 6.1.1 on 2026-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tizim paroli'),
        ),
    ]
